// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARbqcksnYa3jQ7gzTSI5yw5En7gaHDk4g',
    appId: '1:302157060629:web:9fced71d3c72126cfc0c1c',
    messagingSenderId: '302157060629',
    projectId: 'collectionnest-bb936',
    authDomain: 'collectionnest-bb936.firebaseapp.com',
    storageBucket: 'collectionnest-bb936.firebasestorage.app',
    measurementId: 'G-CDSBPLTCKF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEstAaeaYAqe1_QDS0c1UNuiftuqWiXTU',
    appId: '1:302157060629:ios:298fd8349849f135fc0c1c',
    messagingSenderId: '302157060629',
    projectId: 'collectionnest-bb936',
    storageBucket: 'collectionnest-bb936.firebasestorage.app',
    iosBundleId: 'com.CollectionNest.WV77Application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEstAaeaYAqe1_QDS0c1UNuiftuqWiXTU',
    appId: '1:302157060629:ios:569dcfd1e3624946fc0c1c',
    messagingSenderId: '302157060629',
    projectId: 'collectionnest-bb936',
    storageBucket: 'collectionnest-bb936.firebasestorage.app',
    iosBundleId: 'com.example.vitaTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARbqcksnYa3jQ7gzTSI5yw5En7gaHDk4g',
    appId: '1:302157060629:web:603ba3f0f07bb947fc0c1c',
    messagingSenderId: '302157060629',
    projectId: 'collectionnest-bb936',
    authDomain: 'collectionnest-bb936.firebaseapp.com',
    storageBucket: 'collectionnest-bb936.firebasestorage.app',
    measurementId: 'G-QE60RDCPQ0',
  );
}
